# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
Language.delete_all

Language.create(:name => 'Afghanistan - Dari', :iso_639 => 'prs-AF')
Language.create(:name => 'Afghanistan - Pashto', :iso_639 => 'ps-AF')
Language.create(:name => 'Albania - Albanian', :iso_639 => 'sq-AL')
Language.create(:name => 'Algeria - Arabic', :iso_639 => 'ar-DZ')
Language.create(:name => 'Algeria - Tamazight (Latin)', :iso_639 => 'tzm-DZ')
Language.create(:name => 'Argentina - Spanish', :iso_639 => 'es-AR')
Language.create(:name => 'Armenia - Armenian', :iso_639 => 'hy-AM')
Language.create(:name => 'Australia - English', :iso_639 => 'en-AU')
Language.create(:name => 'Austria - German', :iso_639 => 'de-AT')
Language.create(:name => 'Azerbaijan - Azeri (Cyrillic)', :iso_639 => 'az-AZ')
Language.create(:name => 'Azerbaijan - Azeri (Latin)', :iso_639 => 'az-AZ')
Language.create(:name => 'Bahrain - Arabic', :iso_639 => 'ar-BH')
Language.create(:name => 'Bangladesh - Bengali', :iso_639 => 'bn-BD')
Language.create(:name => 'Belarus - Belarusian', :iso_639 => 'be-BY')
Language.create(:name => 'Belgium - Dutch', :iso_639 => 'nl-BE')
Language.create(:name => 'Belgium - French', :iso_639 => 'fr-BE')
Language.create(:name => 'Belize - English', :iso_639 => 'en-BZ')
Language.create(:name => 'Bolivarian Republic of Venezuela - Spanish', :iso_639 => 'es-VE')
Language.create(:name => 'Bolivia - Quechua', :iso_639 => 'quz-BO')
Language.create(:name => 'Bolivia - Spanish', :iso_639 => 'es-BO')
Language.create(:name => 'Bosnia and Herzegovina - Bosnian (Cyrillic)', :iso_639 => 'bs-BA')
Language.create(:name => 'Bosnia and Herzegovina - Bosnian (Latin)', :iso_639 => 'bs-BA')
Language.create(:name => 'Bosnia and Herzegovina - Croatian', :iso_639 => 'hr-BA')
Language.create(:name => 'Bosnia and Herzegovina - Serbian (Cyrillic)', :iso_639 => 'sr-BA')
Language.create(:name => 'Bosnia and Herzegovina - Serbian (Latin)', :iso_639 => 'sr-BA')
Language.create(:name => 'Brazil - Portuguese', :iso_639 => 'pt-BR')
Language.create(:name => 'Brunei Darussalam - Malay', :iso_639 => 'ms-BN')
Language.create(:name => 'Bulgaria - Bulgarian', :iso_639 => 'bg-BG')
Language.create(:name => 'Cambodia - Khmer', :iso_639 => 'km-KH')
Language.create(:name => 'Canada - English', :iso_639 => 'en-CA')
Language.create(:name => 'Canada - French', :iso_639 => 'fr-CA')
Language.create(:name => 'Canada - Inuktitut (Latin)', :iso_639 => 'iu-CA')
Language.create(:name => 'Canada - Inuktitut (Syllabics)', :iso_639 => 'iu-CA')
Language.create(:name => 'Canada - Mohawk', :iso_639 => 'moh-CA')
Language.create(:name => 'Caribbean - English', :iso_639 => 'en-029')
Language.create(:name => 'Chile - Mapudungun', :iso_639 => 'arn-CL')
Language.create(:name => 'Chile - Spanish', :iso_639 => 'es-CL')
Language.create(:name => 'Colombia - Spanish', :iso_639 => 'es-CO')
Language.create(:name => 'Costa Rica - Spanish', :iso_639 => 'es-CR')
Language.create(:name => 'Croatia - Croatian', :iso_639 => 'hr-HR')
Language.create(:name => 'Czech Republic - Czech', :iso_639 => 'cs-CZ')
Language.create(:name => 'Denmark - Danish', :iso_639 => 'da-DK')
Language.create(:name => 'Dominican Republic - Spanish', :iso_639 => 'es-DO')
Language.create(:name => 'Ecuador - Quechua', :iso_639 => 'quz-EC')
Language.create(:name => 'Ecuador - Spanish', :iso_639 => 'es-EC')
Language.create(:name => 'Egypt - Arabic', :iso_639 => 'ar-EG')
Language.create(:name => 'El Salvador - Spanish', :iso_639 => 'es-SV')
Language.create(:name => 'Estonia - Estonian', :iso_639 => 'et-EE')
Language.create(:name => 'Ethiopia - Amharic', :iso_639 => 'am-ET')
Language.create(:name => 'Faroe Islands - Faroese', :iso_639 => 'fo-FO')
Language.create(:name => 'Finland - Finnish', :iso_639 => 'fi-FI')
Language.create(:name => 'Finland - Sami (Inari)', :iso_639 => 'smn-FI')
Language.create(:name => 'Finland - Sami (Northern)', :iso_639 => 'se-FI')
Language.create(:name => 'Finland - Sami (Skolt)', :iso_639 => 'sms-FI')
Language.create(:name => 'Finland - Swedish', :iso_639 => 'sv-FI')
Language.create(:name => 'France - Alsatian', :iso_639 => 'gsw-FR')
Language.create(:name => 'France - Breton', :iso_639 => 'br-FR')
Language.create(:name => 'France - Corsican', :iso_639 => 'co-FR')
Language.create(:name => 'France - French', :iso_639 => 'fr-FR')
Language.create(:name => 'France - Occitan', :iso_639 => 'oc-FR')
Language.create(:name => 'Georgia - Georgian', :iso_639 => 'ka-GE')
Language.create(:name => 'Germany - German', :iso_639 => 'de-DE')
Language.create(:name => 'Germany - Lower Sorbian', :iso_639 => 'dsb-DE')
Language.create(:name => 'Germany - Upper Sorbian', :iso_639 => 'hsb-DE')
Language.create(:name => 'Greece - Greek', :iso_639 => 'el-GR')
Language.create(:name => 'Greenland - Greenlandic', :iso_639 => 'kl-GL')
Language.create(:name => 'Guatemala - Kiche', :iso_639 => 'qut-GT')
Language.create(:name => 'Guatemala - Spanish', :iso_639 => 'es-GT')
Language.create(:name => 'Honduras - Spanish', :iso_639 => 'es-HN')
Language.create(:name => 'Hong Kong S.A.R. - Chinese (Traditional) Legacy', :iso_639 => 'zh-HK')
Language.create(:name => 'Hungary - Hungarian', :iso_639 => 'hu-HU')
Language.create(:name => 'Iceland - Icelandic', :iso_639 => 'is-IS')
Language.create(:name => 'India - Assamese', :iso_639 => 'as-IN')
Language.create(:name => 'India - Bengali', :iso_639 => 'bn-IN')
Language.create(:name => 'India - English', :iso_639 => 'en-IN')
Language.create(:name => 'India - Gujarati', :iso_639 => 'gu-IN')
Language.create(:name => 'India - Hindi', :iso_639 => 'hi-IN')
Language.create(:name => 'India - Kannada', :iso_639 => 'kn-IN')
Language.create(:name => 'India - Konkani', :iso_639 => 'kok-IN')
Language.create(:name => 'India - Malayalam', :iso_639 => 'ml-IN')
Language.create(:name => 'India - Marathi', :iso_639 => 'mr-IN')
Language.create(:name => 'India - Oriya', :iso_639 => 'or-IN')
Language.create(:name => 'India - Punjabi', :iso_639 => 'pa-IN')
Language.create(:name => 'India - Sanskrit', :iso_639 => 'sa-IN')
Language.create(:name => 'India - Tamil', :iso_639 => 'ta-IN')
Language.create(:name => 'India - Telugu', :iso_639 => 'te-IN')
Language.create(:name => 'Indonesia - Indonesian', :iso_639 => 'id-ID')
Language.create(:name => 'Iran - Persian', :iso_639 => 'fa-IR')
Language.create(:name => 'Iraq - Arabic', :iso_639 => 'ar-IQ')
Language.create(:name => 'Ireland - English', :iso_639 => 'en-IE')
Language.create(:name => 'Ireland - Irish', :iso_639 => 'ga-IE')
Language.create(:name => 'Islamic Republic of Pakistan - Urdu', :iso_639 => 'ur-PK')
Language.create(:name => 'Israel - Hebrew', :iso_639 => 'he-IL')
Language.create(:name => 'Italy - Italian', :iso_639 => 'it-IT')
Language.create(:name => 'Jamaica - English', :iso_639 => 'en-JM')
Language.create(:name => 'Japan - Japanese', :iso_639 => 'ja-JP')
Language.create(:name => 'Jordan - Arabic', :iso_639 => 'ar-JO')
Language.create(:name => 'Kazakhstan - Kazakh', :iso_639 => 'kk-KZ')
Language.create(:name => 'Kenya - Kiswahili', :iso_639 => 'sw-KE')
Language.create(:name => 'Korea - Korean', :iso_639 => 'ko-KR')
Language.create(:name => 'Kuwait - Arabic', :iso_639 => 'ar-KW')
Language.create(:name => 'Kyrgyzstan - Kyrgyz', :iso_639 => 'ky-KG')
Language.create(:name => 'Lao P.D.R. - Lao', :iso_639 => 'lo-LA')
Language.create(:name => 'Latvia - Latvian', :iso_639 => 'lv-LV')
Language.create(:name => 'Lebanon - Arabic', :iso_639 => 'ar-LB')
Language.create(:name => 'Libya - Arabic', :iso_639 => 'ar-LY')
Language.create(:name => 'Liechtenstein - German', :iso_639 => 'de-LI')
Language.create(:name => 'Lithuania - Lithuanian', :iso_639 => 'lt-LT')
Language.create(:name => 'Luxembourg - French', :iso_639 => 'fr-LU')
Language.create(:name => 'Luxembourg - German', :iso_639 => 'de-LU')
Language.create(:name => 'Luxembourg - Luxembourgish', :iso_639 => 'lb-LU')
Language.create(:name => 'Macao S.A.R. - Chinese (Traditional) Legacy', :iso_639 => 'zh-MO')
Language.create(:name => 'Macedonia (FYROM) - Macedonian (FYROM)', :iso_639 => 'mk-MK')
Language.create(:name => 'Malaysia - English', :iso_639 => 'en-MY')
Language.create(:name => 'Malaysia - Malay', :iso_639 => 'ms-MY')
Language.create(:name => 'Maldives - Divehi', :iso_639 => 'dv-MV')
Language.create(:name => 'Malta - Maltese', :iso_639 => 'mt-MT')
Language.create(:name => 'Mexico - Spanish', :iso_639 => 'es-MX')
Language.create(:name => 'Mongolia - Mongolian (Cyrillic)', :iso_639 => 'mn-MN')
Language.create(:name => 'Montenegro - Serbian (Cyrillic)', :iso_639 => 'sr-ME')
Language.create(:name => 'Montenegro - Serbian (Latin)', :iso_639 => 'sr-ME')
Language.create(:name => 'Morocco - Arabic', :iso_639 => 'ar-MA')
Language.create(:name => 'Nepal - Nepali', :iso_639 => 'ne-NP')
Language.create(:name => 'Netherlands - Dutch', :iso_639 => 'nl-NL')
Language.create(:name => 'Netherlands - Frisian', :iso_639 => 'fy-NL')
Language.create(:name => 'New Zealand - English', :iso_639 => 'en-NZ')
Language.create(:name => 'New Zealand - Maori', :iso_639 => 'mi-NZ')
Language.create(:name => 'Nicaragua - Spanish', :iso_639 => 'es-NI')
Language.create(:name => 'Nigeria - Hausa (Latin)', :iso_639 => 'ha-NG')
Language.create(:name => 'Nigeria - Igbo', :iso_639 => 'ig-NG')
Language.create(:name => 'Nigeria - Yoruba', :iso_639 => 'yo-NG')
Language.create(:name => 'Norway - Norwegian (Bokm?l)', :iso_639 => 'nb-NO')
Language.create(:name => 'Norway - Norwegian (Nynorsk)', :iso_639 => 'nn-NO')
Language.create(:name => 'Norway - Sami (Lule)', :iso_639 => 'smj-NO')
Language.create(:name => 'Norway - Sami (Northern)', :iso_639 => 'se-NO')
Language.create(:name => 'Norway - Sami (Southern)', :iso_639 => 'sma-NO')
Language.create(:name => 'Oman - Arabic', :iso_639 => 'ar-OM')
Language.create(:name => 'Panama - Spanish', :iso_639 => 'es-PA')
Language.create(:name => 'Paraguay - Spanish', :iso_639 => 'es-PY')
Language.create(:name => 'Republic of China - Chinese (Simplified) Legacy', :iso_639 => 'zh-CN')
Language.create(:name => 'Republic of China - Mongolian (Traditional Mongolian)', :iso_639 => 'mn-CN')
Language.create(:name => 'Republic of China - Tibetan', :iso_639 => 'bo-CN')
Language.create(:name => 'Republic of China - Uyghur', :iso_639 => 'ug-CN')
Language.create(:name => 'Republic of China - Yi', :iso_639 => 'ii-CN')
Language.create(:name => 'Peru - Quechua', :iso_639 => 'quz-PE')
Language.create(:name => 'Peru - Spanish', :iso_639 => 'es-PE')
Language.create(:name => 'Philippines - Filipino', :iso_639 => 'fil-PH')
Language.create(:name => 'Poland - Polish', :iso_639 => 'pl-PL')
Language.create(:name => 'Portugal - Portuguese', :iso_639 => 'pt-PT')
Language.create(:name => 'Principality of Monaco - French', :iso_639 => 'fr-MC')
Language.create(:name => 'Puerto Rico - Spanish', :iso_639 => 'es-PR')
Language.create(:name => 'Qatar - Arabic', :iso_639 => 'ar-QA')
Language.create(:name => 'Republic of the Philippines - English', :iso_639 => 'en-PH')
Language.create(:name => 'Romania - Romanian', :iso_639 => 'ro-RO')
Language.create(:name => 'Russia - Bashkir', :iso_639 => 'ba-RU')
Language.create(:name => 'Russia - Russian', :iso_639 => 'ru-RU')
Language.create(:name => 'Russia - Tatar', :iso_639 => 'tt-RU')
Language.create(:name => 'Russia - Yakut', :iso_639 => 'sah-RU')
Language.create(:name => 'Rwanda - Kinyarwanda', :iso_639 => 'rw-RW')
Language.create(:name => 'Saudi Arabia - Arabic', :iso_639 => 'ar-SA')
Language.create(:name => 'Senegal - Wolof', :iso_639 => 'wo-SN')
Language.create(:name => 'Serbia - Serbian (Cyrillic)', :iso_639 => 'sr-RS')
Language.create(:name => 'Serbia - Serbian (Latin)', :iso_639 => 'sr-RS')
Language.create(:name => 'Serbia and Montenegro (Former) - Serbian (Cyrillic)', :iso_639 => 'sr-CS')
Language.create(:name => 'Serbia and Montenegro (Former) - Serbian (Latin)', :iso_639 => 'sr-CS')
Language.create(:name => 'Singapore - Chinese (Simplified) Legacy', :iso_639 => 'zh-SG')
Language.create(:name => 'Singapore - English', :iso_639 => 'en-SG')
Language.create(:name => 'Slovakia - Slovak', :iso_639 => 'sk-SK')
Language.create(:name => 'Slovenia - Slovenian', :iso_639 => 'sl-SI')
Language.create(:name => 'South Africa - Afrikaans', :iso_639 => 'af-ZA')
Language.create(:name => 'South Africa - English', :iso_639 => 'en-ZA')
Language.create(:name => 'South Africa - isiXhosa', :iso_639 => 'xh-ZA')
Language.create(:name => 'South Africa - isiZulu', :iso_639 => 'zu-ZA')
Language.create(:name => 'South Africa - Sesotho sa Leboa', :iso_639 => 'nso-ZA')
Language.create(:name => 'South Africa - Setswana', :iso_639 => 'tn-ZA')
Language.create(:name => 'Spain - Basque', :iso_639 => 'eu-ES')
Language.create(:name => 'Spain - Catalan', :iso_639 => 'ca-ES')
Language.create(:name => 'Spain - Galician', :iso_639 => 'gl-ES')
Language.create(:name => 'Spain - Spanish', :iso_639 => 'es-ES')
Language.create(:name => 'Sri Lanka - Sinhala', :iso_639 => 'si-LK')
Language.create(:name => 'Sweden - Sami (Lule)', :iso_639 => 'smj-SE')
Language.create(:name => 'Sweden - Sami (Northern)', :iso_639 => 'se-SE')
Language.create(:name => 'Sweden - Sami (Southern)', :iso_639 => 'sma-SE')
Language.create(:name => 'Sweden - Swedish', :iso_639 => 'sv-SE')
Language.create(:name => 'Switzerland - French', :iso_639 => 'fr-CH')
Language.create(:name => 'Switzerland - German', :iso_639 => 'de-CH')
Language.create(:name => 'Switzerland - Italian', :iso_639 => 'it-CH')
Language.create(:name => 'Switzerland - Romansh', :iso_639 => 'rm-CH')
Language.create(:name => 'Syria - Arabic', :iso_639 => 'ar-SY')
Language.create(:name => 'Syria - Syriac', :iso_639 => 'syr-SY')
Language.create(:name => 'Taiwan - Chinese (Traditional) Legacy', :iso_639 => 'zh-TW')
Language.create(:name => 'Tajikistan - Tajik (Cyrillic)', :iso_639 => 'tg-TJ')
Language.create(:name => 'Thailand - Thai', :iso_639 => 'th-TH')
Language.create(:name => 'Trinidad and Tobago - English', :iso_639 => 'en-TT')
Language.create(:name => 'Tunisia - Arabic', :iso_639 => 'ar-TN')
Language.create(:name => 'Turkey - Turkish', :iso_639 => 'tr-TR')
Language.create(:name => 'Turkmenistan - Turkmen', :iso_639 => 'tk-TM')
Language.create(:name => 'U.A.E. - Arabic', :iso_639 => 'ar-AE')
Language.create(:name => 'Ukraine - Ukrainian', :iso_639 => 'uk-UA')
Language.create(:name => 'United Kingdom - English', :iso_639 => 'en-GB')
Language.create(:name => 'United Kingdom - Scottish Gaelic', :iso_639 => 'gd-GB')
Language.create(:name => 'United Kingdom - Welsh', :iso_639 => 'cy-GB')
Language.create(:name => 'United States - English', :iso_639 => 'en-US')
Language.create(:name => 'United States - Spanish', :iso_639 => 'es-US')
Language.create(:name => 'Uruguay - Spanish', :iso_639 => 'es-UY')
Language.create(:name => 'Uzbekistan - Uzbek (Cyrillic)', :iso_639 => 'uz-UZ')
Language.create(:name => 'Uzbekistan - Uzbek (Latin)', :iso_639 => 'uz-UZ')
Language.create(:name => 'Vietnam - Vietnamese', :iso_639 => 'vi-VN')
Language.create(:name => 'Yemen - Arabic', :iso_639 => 'ar-YE')
Language.create(:name => 'Zimbabwe - English', :iso_639 => 'en-ZW')
